В заданиях этого урока нам предстоит проанализировать данные об американских закусочных. Мы поищем, где можно купить тако в Калифорнии, в какие месяцы чаще всего открывали рестораны и разберем, какие есть подводные камни при работе с pandas.

Данные можно скачать по ссылке.

 

Описание данных:
id - уникальный идентификатор заведения

address - физический адрес заведения

categories - категории заведения (например, "Fast food restaurant").

city - город, в котором заведение находится.

cuisines - кухни, которые практикуются в заведении. Например "Mexican".

dateAdded - дата добавления записи. Будем считать, что она совпадает с датой открытия заведения.

dateUpdated - дата обновления информации о заведении.

latitude - географическая широта.

longitude - географическая долгота.

menus.category - категории пищи в меню.

menus.currency - валюта, в которой принимают оплату.

menus.dateSeen - дата, когда было заведено это меню.

menus.description - описание меню от заведения.

menus.name - название меню.

name - название заведения.

province - область (штат), где находится заведение.

Какие колонки будут выведены при применении метода describe и почему только они?

Метод .describe() считает для каждой численной колонки ее среднее, медиану, стандартное отклонение, мин/макс. значения и квантили. В предложенном датафрейме только две численные колонки, соответственно, будут выведены статистики только по этим двум колонкам.

In [4]:
import pandas as pd
df = pd.read_csv("5-data.csv")

In [2]:
df = df.dropna()
len(df)

1925

Найдите, в каком городе находится ресторан с индексом 404.

В качестве ответа укажите город без кавычек. Например:

Los Angeles


NB! В текущем и последующих заданиях вся работа происходит с изначальным датафреймом. Результат предыдущего задания не учитывается

In [5]:
df.loc[404, "city"]

'Dexter'

Отберите заведения, которые находятся в городе Калифорния ('California'), штат Миссури.  Укажите индексы, под которыми полученные заведения расположены в датафрейме, через запятую и пробел в порядке возрастания. 

Например:

11235, 12457, 77980, 88901

In [7]:
df[(df["city"] == "California")].index

Index([40483, 52930, 52931, 52932, 52933, 52934, 52935, 52936, 52937, 52938,
       52939, 65070],
      dtype='int64')

Отберите заведения Taco Bell в городе Калифорния ('California'), штат Миссури.

Укажите индексы этих заведений через запятую и пробел в порядке возрастания.

10011, 11356, 24461, 31679

Давайте найдем заведения Taco Bell или заведения, которые находятся в городе Нью-Йорк. При этом обязательно, чтобы в названии меню не было Volcano Taco и Fresco Soft Taco (именно таких значений колонки). Данные нужно сохранить в датафрейм result.

Данные загружены в переменную data.

In [9]:

result = df[
    ((df.city == "New York") | (df.name == "Taco Bell")) & ((df["menus.name"] != "Volcano Taco") & (df["menus.name"] != "Fresco Soft Taco"))]

Давайте отберем заведения, где значение валюты, в которой принимают оплату, не пропущено.

Нужно сохранить данные в результирующий датафрейм result.

Данные загружены data.

In [ ]:
import numpy as np
result = df[  (df["menus.currency"].notnull())]
result

Давайте посмотрим, сколько ресторанов принимают оплату в той или иной валюте.

Для этого сгруппируйте данные по валюте и посчитайте количество уникальных id ресторанов. В качестве ответа введите число ресторанов, принимающих оплату в евро.

Попробуйте сделать data['categories'], data[['categories']], посмотрите на тип и на значения их элементов.

Выберете подходящие значения.

Верно! df['categories'] отбирает одну колонку и возвращает Series, таков синтаксис. Но df[['categories']] (обратите внимание на две скобки!) создан, чтобы возвращать множество колонок. Поскольку Series хранит только одну колонку, результатом не может быть Series. В итоге синтаксис через две скобки возвращает pd.DataFrame

Напишите через запятую и пробел 5 городов с наибольшим количеством записей (в порядке убывания количества записей).

Посчитайте, сколько ресторанов Taco Bell находится в каждом городе (id ресторанов могут повторяться). Отберите 5 городов, в которых ресторан встречается чаще всего.

Результат сохраните в переменную result в виде объекта pd.Series, где индексом будет название города, а значением - количество ресторанов в этом городе. Ответ должен быть отсортирован по убыванию количества ресторанов.

Для решения задачи полезно будет вспомнить функцию.

Данные сохранены в переменную data

Давайте найдем рестораны, открытые в октябре.

В качестве ответа отправьте индексы первых пяти записей, соответствующих ресторанам, открытым в октябре (ресторан может повторяться). Ответ запишите через запятую и пробел в порядке возрастания.

Например, для датафрейма, показанного на скрине, в качестве ответа нужно ввести 4, 5, 6, 7, 8

Для работы с датой советуем посмотреть в сторону метода to_datetime.

Отберите рестораны, у которых в колонке categories упоминается Pizza

Укажите индекс 3-го элемента, полученного после фильтрации

В этом задании нужно добавить столбец update_delta с количеством целых дней, полученных от разницы между dateUpdated и dateAdded. Посчитайте среднее и медиану получившейся колонки.

Перечислите значения через пробел (сначала среднее, затем медиану), округлив до 2 знаков. 

NB! Оба значения должны быть введены с десятичным разделителем в виде точки.

В этом задании нужно отобрать записи, у которых более 20 категорий, далее их нужно сгруппировать по провинциям и подсчитать минимальную longitude в каждой. Округлите значения longitude до 3-х знаков после запятой.

Далее сохраните результирующий датафрейм в файл в формате csv с сепаратором ;. Сам датафрейм должен содержать две колонки: province и longitude

Для решения задачи полезно будет ознакомиться с функцией.

Отправьте этот файл в форму ниже.